name: CI
on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm run check-failing-intermittent
      - run: pnpm run check-failing-intermittent
      - run: pnpm run check-failing-intermittent
      - run: pnpm run check-failing-intermittent
